### ISSUE TITLE
Fatal error on reindex command

### ISSUE THREAD

**Issue by olivertedwards** [johannschopplich/kirby-algolia-docsearch#3]
Have been having a great time with this plugin before the summer holidays, and came back to an issue when running `kirby algolia-docsearch:index` to reindex the site I am working on.

Running the command gives me a fatal error related to PSR. I have tested different version of Kirby 3.9, and also 4.0 alpha 4 (which was previously working as well).

Here is the terminal output when executing the CLI index command with plugin v0.4.0.

```zsh
Fatal error: Declaration of Algolia\AlgoliaSearch\Http\Psr7\Uri::getScheme() must be compatible with Psr\Http\Message\UriInterface::getScheme(): string in /Users/drx/Sites/ts/vendor/algolia/algoliasearch-client-php/src/Http/Psr7/Uri.php on line 390
Whoops\Exception\ErrorException: Declaration of Algolia\AlgoliaSearch\Http\Psr7\Uri::getScheme() must be compatible with Psr\Http\Message\UriInterface::getScheme(): string in file /Users/drx/Sites/ts/vendor/algolia/algoliasearch-client-php/src/Http/Psr7/Uri.php on line 390
Stack trace:
  1. Whoops\Exception\ErrorException->() /Users/drx/Sites/ts/vendor/algolia/algoliasearch-client-php/src/Http/Psr7/Uri.php:390
  2. Whoops\Run->handleError() /Users/drx/Sites/ts/vendor/filp/whoops/src/Whoops/Run.php:514
  3. Whoops\Run->handleShutdown() [internal]:0
```

An here is the config file:

```php
<?php

return [
	'languages' => true,
	'johannschopplich.algolia-docsearch'  => [
		'appId' => 'XXX',
		'apiKey' => 'XXX',
		'index' => 'dev_site',
		'content' => 'main',
		'templates' => [
		'article',
		'listing'
		],
		'label' => [
		'default' => [
		  'da' => 'Side',
		  'en' => 'Page'
		],
		'templates' => [
		  'article' => [
		    'da' => 'Artikler',
		    'en' => 'Articles'
		  ],
		  'listing' => [
		    'da' => 'Listing',
		    'en' => 'Listing'
		  ]
		]
		],
	],

];
```

The fatal error occurs both when executing directly with the CLI and through the janitor plugin as described in the readme.

Not sure what is going Johann, any ideas?

Best Oliver

**Comment by johannschopplich** [comment]
Hi there,
thanks for the thorough report! This is an upstream error and will be fixed by the PR https://github.com/algolia/algoliasearch-client-php/pull/717. Unfortunately, it seems to be open for a while…

**Comment by olivertedwards** [comment]
Thank you @johannschopplich, at least that is good to know!

**Comment by johannschopplich** [comment]
@tobimori Should be resolved by https://github.com/algolia/algoliasearch-client-php/pull/717. I have upgraded the Kirby plugin to use the latest Algolia package.

**Comment by olivertedwards** [comment]
Beautiful, @johannschopplich, have a great Monday afternoon :)
